name: Validate

on:
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
      - run: terraform fmt -check
      - run: terraform init -backend=false
      - run: terraform validate
